# Generated by Django 5.0.7 on 2024-08-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='iamge',
            new_name='image',
        ),
    ]
